#!/usr/bin/env python
"""The paper's planned figures and tables (OUTLINE section 2), each from
committed files only: no measurement, no new fit beyond the ones named.

    python scripts/paper/make_paper.py <item> [--out DIR]       # one item
    python scripts/paper/make_paper.py all [--out DIR]          # every item
    python scripts/paper/make_paper.py <item> --plot            # data, then the figure

Items: F1 to F11, T1, T3, T4, T6, T7 (T2 is scripts/paper/table_t2.py; the noise
floors are their own script). Default --out is docs/paper. A figure writes
data/<F>.csv and, with --plot, figures/<F>.png (matplotlib, Agg, no metadata);
a table writes <T>.md (and <T>.csv). Each item's docstring names its inputs.
"""
from __future__ import annotations

import argparse
import csv
import io
import json
import math
import re
import statistics
import subprocess
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "scripts"))

PUB = ROOT / "results/published"
REG = ROOT / "docs/registered"
XM = ROOT / "scripts/scoring/crossmodel"
SC1 = ROOT / "scripts/scoring/rental1"
SC2 = ROOT / "scripts/scoring/rental2"
S27 = PUB / "2026-09-27-nvidia_gh200_480gb-session"
C27 = S27 / "results/2026-09-27-nvidia_gh200_480gb-r3-counters/lock1710"
R1 = PUB / "2026-10-01-nvidia_gh200_480gb-rental1-session"
R2 = PUB / "2026-10-02-nvidia_gh200_480gb-rental2-session"
S22 = PUB / "2026-09-28-nvidia_gh200_480gb-8x22b-session"
ITEMS: dict = {}


def item(fn):
    ITEMS[fn.__name__] = fn
    return fn


def rel(p: Path) -> str:
    return str(Path(p).resolve().relative_to(ROOT))


def write_csv(path: Path, header, rows) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    buf = io.StringIO()
    w = csv.writer(buf, lineterminator="\n")
    w.writerow(header)
    for r in rows:
        w.writerow([f"{x:.6g}" if isinstance(x, float) else x for x in r])
    path.write_text(buf.getvalue())


def read_csv(path: Path) -> list[dict]:
    return list(csv.DictReader(path.read_text().splitlines()))


def write_md(path: Path, title: str, sources: list[str], header, rows, notes=()) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    out = [f"# {title}", "", "Generated by `python scripts/paper/make_paper.py "
           f"{path.stem}`. Sources: " + "; ".join(f"`{s}`" for s in sources) + ".", "",
           "| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    for r in rows:
        out.append("| " + " | ".join(f"{x:.6g}" if isinstance(x, float) else str(x)
                                     for x in r) + " |")
    if notes:
        out += ["", *notes]
    path.write_text("\n".join(out) + "\n")
    write_csv(path.with_suffix(".csv"), header, rows)


# ---------------------------------------------------------------------- figures

@item
def F1(out: Path) -> None:
    """pid-to-tile launch order at G = 1, 2, 4, Mixtral 8x7B (E 8), n = 3, w2, SHARED
    (72 declared slots): every LIVE CTA in launch order, its (pid_m, pid_n), the
    expert that owns its slab and whether it fetches the slab (the first live CTA of
    its (group, slab key)). Walk: `wave_split_bytes.pid_map`; grid rows from the
    2026-09-27 lock-1710 counter pages r3c-g{1,2,4}.json (`per_gemm.w2.grid_size`)."""
    import wave_split_bytes as WSB
    rows = []
    for G in (1, 2, 4):
        page = json.loads((C27 / f"r3c-g{G}.json").read_text())
        cell = next(c for c in page["cells"] if c["arm"] == "shared" and int(c["n"]) == 3)
        grid = int(cell["per_gemm"]["w2"]["grid_size"])
        npn = 64
        pid = np.arange(grid)
        _gid, pm, pn = WSB.pid_map(pid, grid // npn, npn, G)
        live = pm < 8 * 3
        seen = set()
        rank = 0
        for i in np.nonzero(live)[0]:
            m, nn = int(pm[i]), int(pn[i])
            key = (int(i) // (G * npn), m // 3, nn)
            lead = key not in seen
            seen.add(key)
            rows.append((G, rank, int(i), m, nn, m // 3, int(lead)))
            rank += 1
    write_csv(out / "data/F1.csv", ["G", "live_rank", "pid", "pid_m", "pid_n", "expert",
                                    "fetcher"], rows)


def plot_F1(out: Path, plt) -> None:
    d = read_csv(out / "data/F1.csv")
    fig, ax = plt.subplots(1, 3, figsize=(10, 3), sharey=True)
    for a, G in zip(ax, (1, 2, 4)):
        r = [x for x in d if int(x["G"]) == G and int(x["live_rank"]) < 24 * 8]
        a.scatter([int(x["pid_n"]) for x in r], [int(x["pid_m"]) for x in r],
                  c=[int(x["live_rank"]) for x in r], s=8, cmap="viridis")
        f = [x for x in r if x["fetcher"] == "1"]
        a.scatter([int(x["pid_n"]) for x in f], [int(x["pid_m"]) for x in f], marker="x",
                  c="k", s=12)
        a.set_title(f"G = {G}")
        a.set_xlabel("pid_n")
    ax[0].set_ylabel("pid_m")
    fig.tight_layout()
    return fig


def _old_build(pages, p_knee):
    import r3_timing_model as TM
    argv = [*map(str, pages), "--counters", str(C27), "--p-knee", str(p_knee),
            "--no-tail", "--no-dead", "--no-cta-fixed", "--no-cores"]
    return TM.build(TM.build_parser().parse_args(argv))


import contextlib  # noqa: E402


@contextlib.contextmanager
def _old_model():
    """Hold r3_timing_model's switches at the knee's commit (8900699) while pricing
    outside `build`, which restores them on return."""
    import r3_timing_model as TM
    saved = (TM.P_KNEE, TM.TAIL, TM.DEAD, TM.CTA_FIXED, TM.CORES)
    TM.TAIL = TM.DEAD = TM.CTA_FIXED = TM.CORES = False
    try:
        yield
    finally:
        TM.P_KNEE, TM.TAIL, TM.DEAD, TM.CTA_FIXED, TM.CORES = saved


def _p27_1710():
    import r3_timing_model as TM
    return [p.path for p in TM.discover_timed([S27 / "results"])
            if p.label == "VALID" and p.locked and next(iter(p.clocks)) == 1710.0]


@item
def F2(out: Path) -> None:
    """Soft against hard max on the 2026-09-27 board. Two refits of
    `r3_timing_model.build` on its VALID lock-1710 timed pages and lock-1710 counter
    pages, the model as at the knee's commit 8900699 (--no-tail --no-dead
    --no-cta-fixed --no-cores), at p = 14 and p = inf: per cell measured and both
    predictions. Plus, at G = 3 n = 2, every live w1 CTA's m / f (its window's DRAM
    time over its floor) at the p = 14 fit's c and bw. Writes F2.csv (cells) and
    F2_mf.csv (CTAs)."""
    import r3_timing_model as TM
    pages = _p27_1710()
    soft, hard = _old_build(pages, 14.0), _old_build(pages, math.inf)
    rows = []
    with _old_model():
        for cs, ch in zip(soft["cells"], hard["cells"], strict=True):
            assert cs.key == ch.key
            TM.P_KNEE = 14.0
            ps = TM.call_ms(soft["main"].x, cs, soft["ctx"], soft["k_w"])
            TM.P_KNEE = math.inf
            ph = TM.call_ms(hard["main"].x, ch, hard["ctx"], hard["k_w"])
            rows.append((cs.arm, cs.G, cs.n, int(cs.fit), cs.ms, ps, ph))
    write_csv(out / "data/F2.csv", ["arm", "G", "n", "fitted", "measured_ms", "p14_ms",
                                    "pinf_ms"], rows)
    ctx, x = soft["ctx"], soft["main"].x
    c_ns, bw = float(x[1]), float(x[2])
    mf = []
    for cell in soft["cells"]:
        if (cell.G, cell.n) != (3, 2):
            continue
        g = "w1"
        w = TM.window_width(soft["k_w"], ctx.sms, ctx.occupancy[g])
        win = TM.window(cell.arm, cell.declared, 3, 2, g, w)
        with TM.cta_fixed(False):
            f = TM.wave_q(win.live, ctx.sms) * TM.floor_ksteps(g) * c_ns * 1e-6 / ctx.sms
        m = (cell.sigma[g] * win.mean + TM.OUT_TILE) / (bw * 1e6)
        mf += [(cell.arm, i, float(v)) for i, v in enumerate(m / f)]
    write_csv(out / "data/F2_mf.csv", ["arm", "cta", "m_over_f"], mf)


def plot_F2(out: Path, plt):
    d = read_csv(out / "data/F2_mf.csv")
    fig, ax = plt.subplots(figsize=(5, 3))
    for arm in ("native", "shared", "private"):
        v = [float(r["m_over_f"]) for r in d if r["arm"] == arm]
        ax.hist(v, bins=50, histtype="step", label=arm)
    ax.set_xlabel("m / f per CTA, G = 3, n = 2, w1")
    ax.legend()
    fig.tight_layout()
    return fig


@item
def F3(out: Path) -> None:
    """Measured and modelled R3 ladders on the 2026-09-27 board: every cell of the
    VALID lock-1710 timed pages (G = 2, 3, 4, 8, 32 at 1710; the board timed no
    other G at 1710) against the HEAD timing model refitted on those pages
    (`r3_timing_model.build`, default flags)."""
    import r3_timing_model as TM
    R = TM.build(TM.build_parser().parse_args([*map(str, _p27_1710()), "--counters", str(C27)]))
    rows = [(c.arm, c.G, c.n, int(c.fit), c.ms, TM.call_ms(R["main"].x, c, R["ctx"], R["k_w"]))
            for c in R["cells"]]
    write_csv(out / "data/F3.csv", ["arm", "G", "n", "fitted", "measured_ms", "model_ms"], rows)


def plot_F3(out: Path, plt):
    d = read_csv(out / "data/F3.csv")
    Gs = sorted({int(r["G"]) for r in d})
    fig, ax = plt.subplots(1, len(Gs), figsize=(3 * len(Gs), 3), sharey=True)
    for a, G in zip(ax, Gs):
        for arm in ("native", "shared", "private"):
            r = [x for x in d if int(x["G"]) == G and x["arm"] == arm]
            a.plot([int(x["n"]) for x in r], [float(x["measured_ms"]) for x in r], "o", ms=3)
            a.plot([int(x["n"]) for x in r], [float(x["model_ms"]) for x in r], "-", lw=1)
        a.set_title(f"G = {G}")
        a.set_xlabel("n")
    ax[0].set_ylabel("ms")
    fig.tight_layout()
    return fig


#: The registered P1 numbers (2026-09-27 session README:74-77; 1605 also
#: scripts/r3_timing_model.py P1 comment): G=4 SHARED slope at eta 1 and eta 0.35.
P1_REG = {1410: (0.6654, 0.5878), 1500: (0.6259, 0.5754), 1605: (0.5854, 0.5621)}


@item
def F4(out: Path) -> None:
    """The G=4 SHARED slope (np.polyfit over treads 2 to 6, as `r3_timing_model`'s
    P1) on the 2026-09-27 G=4 pages locked at 1410, 1500, 1605 and 1710, against the
    registered eta 1 and eta 0.35 slopes (P1_REG, the session README)."""
    import r3_timing_model as TM
    rows = []
    for p in TM.discover_timed([S27 / "results"]):
        if p.G != 4 or p.label != "VALID" or not p.locked:
            continue
        f = int(next(iter(p.clocks)))
        s = float(np.polyfit(range(2, 7), [p.rows[("shared", n)][0] for n in range(2, 7)], 1)[0])
        e1, e35 = P1_REG.get(f, ("", ""))
        rows.append((f, s, e1, e35))
    write_csv(out / "data/F4.csv", ["lock_mhz", "measured_slope_ms", "eta1_registered",
                                    "eta035_registered"], sorted(rows))


def plot_F4(out: Path, plt):
    d = read_csv(out / "data/F4.csv")
    fig, ax = plt.subplots(figsize=(4, 3))
    f = [int(r["lock_mhz"]) for r in d]
    ax.plot(f, [float(r["measured_slope_ms"]) for r in d], "ko", label="measured")
    k = [r for r in d if r["eta1_registered"]]
    ax.plot([int(r["lock_mhz"]) for r in k], [float(r["eta1_registered"]) for r in k], "-",
            label="eta 1")
    ax.plot([int(r["lock_mhz"]) for r in k], [float(r["eta035_registered"]) for r in k], "--",
            label="eta 0.35")
    ax.set_xlabel("SM lock (MHz)")
    ax.set_ylabel("ms per tread")
    ax.legend()
    fig.tight_layout()
    return fig


F5_MODELS = [("mixtral-8x22b", "8x22b.registered.json", "predicted bytes"),
             ("qwen2-57b-a14b", "qwen2.registered.json", "predicted bytes"),
             ("olmoe-1b-7b", "olmoe-1b-7b.score.json", "own counted bytes"),
             ("qwen1.5-moe-a2.7b", "qwen1.5-moe-a2.7b.score.json", "own counted bytes"),
             ("phi-3.5-moe", "phi-3.5-moe.score.json", "own counted bytes"),
             ("jetmoe-8b", "jetmoe-8b.score.json", "own counted bytes")]


@item
def F5(out: Path) -> None:
    """Per-cell residual (predicted / measured - 1) of every registered time test,
    from the committed outputs in scripts/scoring/crossmodel/ (8x22B and Qwen2-57B:
    the registered JSON's T, predicted bytes; the other four: cross_model_score.py
    at the registration's commit, own counted bytes). Granite-3B: no VALID page."""
    rows = []
    for model, f, kind in F5_MODELS:
        d = json.loads((XM / f).read_text())
        cells = d["time_predicted_bytes"]["cells"] if "time_predicted_bytes" in d else d["cells"]
        for c in cells:
            rows.append((model, kind, c["arm"], c["G"], c["n"], c["measured_ms"],
                         c.get("registered_ms", c.get("predicted_ms")), c["resid"]))
    write_csv(out / "data/F5.csv", ["model", "bytes", "arm", "G", "n", "measured_ms",
                                    "predicted_ms", "resid"], rows)


def plot_F5(out: Path, plt):
    d = read_csv(out / "data/F5.csv")
    models = list(dict.fromkeys(r["model"] for r in d))
    fig, ax = plt.subplots(1, len(models), figsize=(3 * len(models), 3), sharey=True)
    for a, m in zip(ax, models):
        for arm in ("native", "shared", "private"):
            r = [x for x in d if x["model"] == m and x["arm"] == arm]
            a.plot([int(x["n"]) for x in r], [100 * float(x["resid"]) for x in r], ".",
                   label=arm)
        for y in (-5, -2, 2, 5):
            a.axhline(y, lw=0.5, c="grey")
        a.set_title(m, fontsize=8)
        a.set_xlabel("n")
    ax[0].set_ylabel("predicted / measured - 1 (%)")
    fig.tight_layout()
    return fig


@item
def F6(out: Path) -> None:
    """Floor per CTA k-step against k-steps per CTA S, every GEMM the cross-model
    registrations scored, base and lock captures (scripts/scoring/crossmodel/
    *.registered.json `floor`), plus rental 1's tp8 F4 (scripts/scoring/rental1/
    floor.score.json). Curves 344.1 + 520 / S (w1) and 344.1 + 979 / S (w2): c and F
    of docs/registered/README.md:179-181."""
    rows = []
    for f in sorted(XM.glob("*.registered.json")):
        d = json.loads(f.read_text())
        for cap, res in d["floor"].items():
            if not res:
                continue
            for g, r in res.items():
                rows.append((d["model"], g, d["ksteps"][g],
                             "lock" if "lock" in cap else "base", r["slope"], r["registered"]
                             or "", r["verdict"]))
    fl = json.loads((SC1 / "floor.score.json").read_text())["captures"]
    S = {"w1": 64, "w2": 28}  # mixtral-8x7b-tp8: w1 K 4096, w2 K 1792 (moe/spec.py)
    for cap in ("r3f-g64", "r3f-g64-lock1710"):
        for g, r in fl[cap]["F4"].items():
            rows.append(("mixtral-8x7b-tp8", g, S[g], "lock" if "lock" in cap else "base",
                         r["slope"], r["reg"], r["verdict"]))
    write_csv(out / "data/F6.csv", ["model", "gemm", "S", "capture", "floor_cycles",
                                    "registered", "verdict"], rows)


def plot_F6(out: Path, plt):
    d = read_csv(out / "data/F6.csv")
    fig, ax = plt.subplots(figsize=(5, 3.5))
    for cap, mk in (("base", "o"), ("lock", "x")):
        for g, col in (("w1", "C0"), ("w2", "C1")):
            r = [x for x in d if x["capture"] == cap and x["gemm"] == g]
            ax.plot([int(x["S"]) for x in r], [float(x["floor_cycles"]) for x in r], mk, c=col)
    s = np.linspace(8, 256, 200)
    ax.plot(s, 344.1 + 520 / s, c="C0", lw=1)
    ax.plot(s, 344.1 + 979 / s, c="C1", lw=1)
    ax.set_xscale("log")
    ax.set_xlabel("k-steps per CTA S")
    ax.set_ylabel("cycles per CTA k-step")
    fig.tight_layout()
    return fig


@item
def F7(out: Path) -> None:
    """PRIVATE bytes, measured q (`dram_counter_route.r3_q`, lock-1710 counter pages)
    against the registered q, every model and both GEMMs (scripts/scoring/crossmodel/
    *.registered.json `bytes.cells`)."""
    rows = []
    for f in sorted(XM.glob("*.registered.json")):
        d = json.loads(f.read_text())
        for c in (d.get("bytes") or {}).get("cells", []):
            if c["arm"] == "private":
                rows.append((d["model"], c["gemm"], c["G"], c["n"], c["q_meas"], c["q_reg"],
                             c["rel"]))
    write_csv(out / "data/F7.csv", ["model", "gemm", "G", "n", "q_measured", "q_registered",
                                    "rel"], rows)


def plot_F7(out: Path, plt):
    d = read_csv(out / "data/F7.csv")
    fig, ax = plt.subplots(figsize=(4, 4))
    for g in ("w1", "w2"):
        r = [x for x in d if x["gemm"] == g]
        ax.plot([float(x["q_measured"]) for x in r], [float(x["q_registered"]) for x in r], ".",
                label=g)
    lim = np.array([0.9, 13])
    ax.plot(lim, lim, "k-", lw=0.5)
    ax.plot(lim, lim * 1.05, "k:", lw=0.5)
    ax.plot(lim, lim * 0.95, "k:", lw=0.5)
    ax.set_xlabel("measured q")
    ax.set_ylabel("registered q")
    ax.legend()
    fig.tight_layout()
    return fig


@item
def F8(out: Path) -> None:
    """L2 survival s against n at G = 1: rental 1's measured s and the H1 / H0
    predictions (scripts/scoring/rental1/l2.score.json `s`), and rental 2's knob
    pages (scripts/scoring/rental2/knobs.score.json `tests.*.measured`)."""
    rows = []
    l2 = json.loads((SC1 / "l2.score.json").read_text())["s"]
    for name, v in l2.items():
        for i, n in enumerate(range(2, 10)):
            rows.append(("rental1", name, n, v["meas"][i], (v.get("H1") or [""] * 8)[i],
                         (v.get("H0") or [""] * 8)[i]))
    kn = json.loads((SC2 / "knobs.score.json").read_text())["tests"]
    for name, v in kn.items():
        for n, s in (v.get("measured") or {}).items():
            if isinstance(s, (int, float)):
                rows.append(("rental2", name, int(n), float(s), "", ""))
    write_csv(out / "data/F8.csv", ["rental", "series", "n", "s", "H1", "H0"], rows)


def plot_F8(out: Path, plt):
    d = read_csv(out / "data/F8.csv")
    fig, ax = plt.subplots(figsize=(5, 3.5))
    for name in dict.fromkeys(r["series"] for r in d):
        r = [x for x in d if x["series"] == name]
        if name in ("tp2 w2", "tp4 w1", "sameboard 8x7B w2") or r[0]["rental"] == "rental2":
            ax.plot([int(x["n"]) for x in r], [float(x["s"]) for x in r], ".-", label=name)
    ax.set_xlabel("n")
    ax.set_ylabel("s")
    ax.legend(fontsize=6)
    fig.tight_layout()
    return fig


@item
def F9(out: Path) -> None:
    """Rental 2's launch-floor rerun: per (model, mode, arm, n) the median ms_p50 over
    repeats (cells.csv), H_pre (hostprobe.csv) and C_reg (the registration JSON),
    Granite-3B and tp8."""
    reg = json.loads((REG / "2026-10-01-rental2-launch2-gh200.json").read_text())
    creg = reg["C_reg_ms"]
    base = R2 / "results/2026-10-02-nvidia_gh200_480gb-launch-floor-r2"
    rows = []
    for model in ("granite-3.0-3b-a800m", "mixtral-8x7b-tp8"):
        cells = read_csv(base / model / "cells.csv")
        hp = {(r["mode"], r["arm"], int(r["tiles"])): float(r["H_pre_ms"])
              for r in read_csv(base / model / "hostprobe.csv") if r["H_pre_ms"]}
        keys = sorted({(r["mode"], r["arm"], int(r["tiles"])) for r in cells})
        for mode, arm, n in keys:
            v = [float(r["ms_p50"]) for r in cells
                 if (r["mode"], r["arm"], int(r["tiles"])) == (mode, arm, n) and r["ms_p50"]]
            c = _creg(creg, model, arm, n)
            rows.append((model, mode, arm, n, statistics.median(v), hp.get((mode, arm, n), ""),
                         c))
    write_csv(out / "data/F9.csv", ["model", "mode", "arm", "n", "ms_p50_median", "H_pre_ms",
                                    "C_reg_ms"], rows)


def _creg(creg, model, arm, n):
    m = creg.get(model) if isinstance(creg, dict) else None
    if isinstance(m, dict):
        a = m.get(arm)
        if isinstance(a, list) and n - 1 < len(a):
            return a[n - 1]
        if isinstance(a, dict):
            return a.get(str(n), "")
    return ""


def plot_F9(out: Path, plt):
    d = read_csv(out / "data/F9.csv")
    fig, ax = plt.subplots(1, 2, figsize=(9, 3.5))
    for a, model in zip(ax, ("granite-3.0-3b-a800m", "mixtral-8x7b-tp8")):
        for mode in ("E0", "E240", "E480", "GR"):
            r = [x for x in d if x["model"] == model and x["mode"] == mode and x["arm"] == "shared"]
            a.plot([int(x["n"]) for x in r], [float(x["ms_p50_median"]) for x in r], ".-",
                   label=mode)
        r = [x for x in d if x["model"] == model and x["mode"] == "E240" and x["arm"] == "shared"
             and x["C_reg_ms"]]
        a.plot([int(x["n"]) for x in r], [float(x["C_reg_ms"]) for x in r], "k--", label="C_reg")
        a.set_title(f"{model}, SHARED", fontsize=8)
        a.set_xlabel("n")
        a.legend(fontsize=6)
    fig.tight_layout()
    return fig


@item
def F10(out: Path) -> None:
    """Duration against cycles for rental 2's tp4 floor captures at 1005 and 1710:
    per cell and GEMM `gpu__time_duration.sum`, `sm__cycles_elapsed.avg` and
    `lts__cycles_elapsed.avg`, with the least-squares fits duration = t0 + cycles / f
    for SM and L2 cycles per capture (the fit FL1 used; the gate audit's refit)."""
    rows, fits = [], []
    for cap in ("2026-10-02-nvidia_gh200_480gb-mixtral-8x7b-tp4-floor-r3-counters/r3f-g64-lock1710.json",
                "2026-10-02-nvidia_gh200_480gb-mixtral-8x7b-tp4-floor1005-r3-counters/r3f-g64-lock1005.json"):
        p = R2 / "results" / cap
        d = json.loads(p.read_text())
        lock = d["clock"]["lock_mhz"]
        for g in ("w1", "w2"):
            pts = []
            for c in d["cells"]:
                pg = c["per_gemm"].get(g)
                if not pg:
                    continue
                t, sm, lt = (pg.get("gpu__time_duration.sum"), pg.get("sm__cycles_elapsed.avg"),
                             pg.get("lts__cycles_elapsed.avg"))
                rows.append((lock, g, c["n"], t, sm, lt))
                pts.append((t, sm, lt))
            for k, name in ((1, "sm"), (2, "l2")):
                xs = [q[k] for q in pts if q[k]]
                ys = [q[0] for q in pts if q[k]]
                b, t0 = np.polyfit(xs, ys, 1)
                fits.append((lock, g, name, 1e3 / b, t0 / 1e3))
    write_csv(out / "data/F10.csv", ["lock_mhz", "gemm", "n", "duration_ns", "sm_cycles",
                                     "l2_cycles"], rows)
    write_csv(out / "data/F10_fits.csv", ["lock_mhz", "gemm", "cycles", "f_mhz", "t0_us"], fits)


def plot_F10(out: Path, plt):
    d = read_csv(out / "data/F10.csv")
    fig, ax = plt.subplots(figsize=(5, 3.5))
    for lock in dict.fromkeys(r["lock_mhz"] for r in d):
        for g in ("w1", "w2"):
            r = [x for x in d if x["lock_mhz"] == lock and x["gemm"] == g]
            ax.plot([float(x["sm_cycles"]) for x in r], [float(x["duration_ns"]) / 1e3 for x in r],
                    "o", ms=3, label=f"{lock} MHz {g}")
    ax.set_xlabel("sm__cycles_elapsed.avg")
    ax.set_ylabel("duration (us)")
    ax.legend(fontsize=6)
    fig.tight_layout()
    return fig


@item
def F11(out: Path) -> None:
    """SM clock, power and the software power cap flag (bit 0x4 of
    clocks_event_reasons.active) over 8x22B's deep G = 4 ladders, every nvidia-smi
    row of session/locked-r3/*-deep*/smi.csv."""
    rows = []
    for f in sorted((S22 / "session/locked-r3").glob("*deep*/smi.csv")):
        tag = f.parent.name.rsplit("-", 1)[-1]
        lines = f.read_text().splitlines()
        for i, ln in enumerate(lines[1:]):
            x = [v.strip() for v in ln.split(",")]
            if len(x) < 8 or not x[1].endswith("MHz"):
                continue
            reasons = int(x[7], 16)
            rows.append((tag, i, int(x[1].split()[0]), float(x[3].split()[0]),
                         int(bool(reasons & 0x4))))
    write_csv(out / "data/F11.csv", ["ladder", "row", "sm_mhz", "power_w", "sw_power_cap_0x4"],
              rows)


def plot_F11(out: Path, plt):
    d = read_csv(out / "data/F11.csv")
    fig, ax = plt.subplots(2, 1, figsize=(7, 4), sharex=True)
    for lad in dict.fromkeys(r["ladder"] for r in d):
        r = [x for x in d if x["ladder"] == lad]
        ax[0].plot([int(x["row"]) for x in r], [int(x["sm_mhz"]) for x in r], lw=0.5, label=lad)
        ax[1].plot([int(x["row"]) for x in r], [float(x["power_w"]) for x in r], lw=0.5)
        cap = [x for x in r if x["sw_power_cap_0x4"] == "1"]
        ax[1].plot([int(x["row"]) for x in cap], [float(x["power_w"]) for x in cap], "r.", ms=2)
    ax[0].set_ylabel("SM MHz")
    ax[1].set_ylabel("W (red: 0x4)")
    ax[1].set_xlabel("nvidia-smi row")
    ax[0].legend(fontsize=6)
    fig.tight_layout()
    return fig


# ---------------------------------------------------------------------- tables

T1_MODELS = ["mixtral-8x7b", "mixtral-8x22b", "qwen2-57b-a14b", "olmoe-1b-7b",
             "qwen1.5-moe-a2.7b", "phi-3.5-moe", "jetmoe-8b", "granite-3.0-3b-a800m",
             "mixtral-8x7b-tp8", "mixtral-8x7b-tp4", "mixtral-8x7b-tp2", "granite-3.0-1b-a400m"]


@item
def T1(out: Path) -> None:
    """Models and shapes: `moe.spec.MODEL_CONFIGS` and `dram_counter_route.r3_byte_model`
    at BLOCK_M 32 / BLOCK_N 64 / BLOCK_K 64, bf16."""
    import dram_counter_route as DCR
    from moe.spec import MODEL_CONFIGS
    rows = []
    for m in T1_MODELS:
        c = MODEL_CONFIGS[m]
        bm = DCR.r3_byte_model(c, "bf16", 32)
        H, F = c.hidden_size, c.intermediate_size
        rows.append((m, c.num_experts, c.top_k, H, F, f"{H} / {2 * F // 64}", f"{F} / {H // 64}",
                     f"{H // 64} / {F // 64}", f"{bm['W_w1'] / 1e9:.3f} / {bm['W_w2'] / 1e9:.3f}"))
    write_md(out / "T1.md", "T1: models and shapes",
             ["moe/spec.py", "scripts/dram_counter_route.py r3_byte_model"],
             ["model", "E", "top-k", "H", "F", "w1 K / N-tiles", "w2 K / N-tiles",
              "k-steps per CTA S w1 / w2", "weight GB w1 / w2"], rows)


T3_COMMITS = [("f97df00", "r3_lock_fit (lock gate fit)"), ("8900699", "knee P_KNEE = 14"),
              ("e5eced6", "MIX byte view"), ("5474743", "TAIL partial-wave lifetime"),
              ("fb440c5", "stage 3 A law"), ("b994aa0", "lock read-back"),
              ("ea2c77c", "dead-CTA term"), ("15a9533", "LATER_MISS capacity rule"),
              ("0f77622", "per-CTA fixed cost F"), ("a156392", "4+-wave floor estimator"),
              ("79c5034", "floor-only sessions"), ("CORES", "co-residency law (2026-09-30)")]
#: The registration that first carried each term (docs/registered/README.md).
T3_FIRST = {"8900699": "2026-09-27-mixtral-8x22b", "e5eced6": "2026-09-27-mixtral-8x22b",
            "5474743": "2026-09-28-qwen2-57b-a14b", "fb440c5": "2026-09-28-qwen2-57b-a14b",
            "15a9533": "2026-09-29-olmoe-1b-7b", "ea2c77c": "2026-09-29-olmoe-1b-7b",
            "0f77622": "2026-09-29 four held-out", "a156392": "2026-09-29 Granite estimator note",
            "79c5034": "2026-09-30 floor-only sessions", "CORES": "2026-09-30-mixtral-8x7b-tp8-floor"}


@item
def T3(out: Path, repo: Path | None = None) -> None:
    """Model version timeline: each commit's date and subject from `git show -s` in
    the repository (--repo, default this tree; the committed T3.md was made with
    --repo pointing at a full clone of the study's repository; a commit git cannot resolve prints
    `not in this checkout`), and the registration that first carried the term."""
    repo = repo or ROOT
    rows = []
    for c, what in T3_COMMITS:
        date = subj = "not in this checkout"
        if c != "CORES":
            p = subprocess.run(["git", "-C", str(repo), "show", "-s", "--format=%cI%x09%s", c],
                               capture_output=True, text=True)
            if p.returncode == 0 and "\t" in p.stdout:
                date, subj = p.stdout.strip().split("\t", 1)
                subj = subj[:90]
        else:
            date, subj = "2026-09-30", "CORES in scripts/r3_timing_model.py"
        rows.append((c, what, date, subj, T3_FIRST.get(c, "")))
    write_md(out / "T3.md", "T3: model version timeline", ["git log", "docs/registered/README.md"],
             ["commit", "term", "commit date", "subject", "first registration carrying it"], rows)


@item
def T4(out: Path) -> None:
    """GH200 sessions: date, board hash (`dram_counter_route.board` of the card UUID
    on the session's pages), run commit (session/commit.txt or the pages' git_sha),
    models (the pages' `design.model` / `plan.model`), page count."""
    import dram_counter_route as DCR
    rows = []
    for s in sorted(PUB.glob("*-nvidia_gh200_480gb*-session")):
        boards, models, shas = set(), set(), set()
        pages = list(s.rglob("r3c-g*.json")) + list(s.rglob("r3f-*.json"))
        for p in pages:
            if p.suffix != ".json":
                continue
            d = json.loads(p.read_text())
            uuid = (d.get("card") or {}).get("uuid")
            if uuid:
                boards.add(DCR.board(uuid))
            m = (d.get("design") or d.get("plan") or {}).get("model")
            if m:
                models.add(m)
            if d.get("git_sha"):
                shas.add(str(d["git_sha"])[:7])
        ct = s / "session/commit.txt"
        commit = ct.read_text().split()[0][:7] if ct.exists() and ct.read_text().strip() \
            else ", ".join(sorted(shas))
        rows.append((s.name[:10], s.name, ", ".join(sorted(boards)), commit,
                     ", ".join(sorted(models)), len(pages)))
    write_md(out / "T4.md", "T4: GH200 sessions",
             ["results/published/*-nvidia_gh200_480gb*-session"],
             ["date", "session", "board", "commit", "models", "counter pages"], rows,
             notes=["Minutes and cost per session are in each session README "
                    "(`session/README.md`, \"Where it came from\").",
                    f"Distinct boards: {len({b for r in rows for b in r[2].split(', ') if b})}."])


@item
def T6(out: Path) -> None:
    """K1 to K5, rental 2 part 3: scripts/scoring/rental2/const.score.json `K`."""
    K = json.loads((SC2 / "const.score.json").read_text())["K"]
    k3 = K["K3"]
    rows = [("K1", f"fraction over 5000 cycles {K['K1']['fraction_over']:.4f} of {K['K1']['cells']}",
             K["K1"]["verdict"]),
            ("K2", f"pooled w2 Z / u {K['K2']['pooled']:.4f} ({', '.join(f'{v:.4f}' for v in K['K2']['values'])})",
             K["K2"]["verdict"]),
            ("K3", f"pooled r {k3['pooled_r']:.4f}, rho_f {k3['pooled_rho_f']:.4f}, sigma {k3['sigma']:.4f}",
             "; ".join(f"{k} {v}" for k, v in k3.items() if "verdict" in k)),
            ("K4", f"within 0.2 u {K['K4']['fraction_within_0.2u']:.4f}, at >= 0.3 u {K['K4']['fraction_ge_0.3u']:.4f}",
             K["K4"]["verdict"]),
            ("K5", "RECORD", K["K5"]["verdict"])]
    write_md(out / "T6.md", "T6: the per-GEMM constant, K1 to K5",
             ["scripts/scoring/rental2/const.score.json"], ["test", "numbers", "verdict"], rows)


@item
def T7(out: Path) -> None:
    """tp8 F1 to F4 under the co-residency law and its three rivals:
    scripts/scoring/rental1/floor.score.json, every capture (registered numbers from
    docs/registered/2026-09-30-mixtral-8x7b-tp8-floor-gh200.json, carried there)."""
    fl = json.loads((SC1 / "floor.score.json").read_text())["captures"]
    rows = []
    for cap, d in fl.items():
        f1, f2 = d["F1"], d["F2"]
        for law in ("cores", "old_lifetime", "cores_per_lead", "throughput"):
            rows.append((cap, "F1 D", law, f1["registered"][law], f1["D"],
                         "inside" if f1["inside"][law] else "outside"))
        for law, dev in f2["rivals_dev"].items():
            rows.append((cap, "F2 w1 n=2", law, f2["repriced"][law], f2["cycles"], f"{100 * dev:+.2f}%"))
        rows.append((cap, "F3", "cores", "", "", f"{d['F3']['verdict']}: " + ", ".join(
            f"n={n} {g} {v:+.2f}%" for n, g, v in d["F3"]["outside_reg"])))
        for g, r in d["F4"].items():
            rows.append((cap, f"F4 {g}", "cores", r["reg"], r["slope"],
                         f"{r['verdict']} ({100 * r['dev']:+.2f}%)"))
    write_md(out / "T7.md", "T7: tp8 floor, F1 to F4 under the law and three rivals",
             ["scripts/scoring/rental1/floor.score.json",
              "docs/registered/2026-09-30-mixtral-8x7b-tp8-floor-gh200.json"],
             ["capture", "test", "law", "predicted", "measured", "result"], rows)


# ---------------------------------------------------------------------- main

def plot(name: str, out: Path) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    fig = globals()[f"plot_{name}"](out, plt)
    (out / "figures").mkdir(parents=True, exist_ok=True)
    fig.savefig(out / "figures" / f"{name}.png", dpi=110, metadata={"Software": None})
    plt.close(fig)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("item", choices=[*ITEMS, "all"])
    ap.add_argument("--out", type=Path, default=ROOT / "docs/paper")
    ap.add_argument("--plot", action="store_true", help="also draw the figure (F items)")
    ap.add_argument("--repo", type=Path, default=None,
                    help="T3 only: the git checkout whose history dates the commits")
    a = ap.parse_args(argv)
    for name in (ITEMS if a.item == "all" else [a.item]):
        if name == "T3":
            T3(a.out, a.repo)
        else:
            ITEMS[name](a.out)
        if a.plot and name.startswith("F"):
            plot(name, a.out)
        print(f"{name}: written under {a.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
